### ISSUE TITLE
Feature Request: path replacement in custom data attributes

### ISSUE THREAD

**Issue by ccbayer** [qwales1/gulp-assetpaths#19]
I often use lazy loading or other techniques that use data attributes to image paths; it'd be cool if an option would be to pass these attributes as an object or array that your plugin will replace paths inside of.

**Comment by qwales1** [comment]
@ccbayer yeah I think that would be a better approach overall. I don't use this plugin much myself anymore, but I definitely like the idea of making it more explicit what should get replaced. [gulp-regex-replace](https://github.com/mikrofusion/gulp-regex-replace) looks interesting. It has the option to pass in the regular expression you want to match and lets you use a capture group to only replace that portion which would be perfect for the data attribute example. This plugin may be able to use that under the hood. Maybe could look something like ...

```javascript

var config = {
   oldDomain: oldDomain,
   newDomain: newDomain,
   docRoot: 'public_html',
   //list of attrs you want to change path of
   replace: ['data-lazyload', 'src', 'href' ...etc],
   //don't change path if the file is in these types
   excludeFiletypes: ['css', ...etc],
   //maybe add ability to specify template delimiters
   templateDelimiters: [
     { open: '{{' , close: '}}'},
     { open: '<?php', close: '?>'},
     { open: '<%', close: '%>}'}
   ]
}

gulp.src('index.html')
  .pipe(assetpaths(config))
  .pipe(gulp.dest('./dist'))
```

**Comment by qwales1** [comment]
@ccbayer realized that it couldn't change that much because not everything it replaces is an attribute, for example css files, but version 0.3.0 allows you to pass an array of customAttributes and it will replace them. Let me know if you run into any issues with it.

**Comment by ccbayer** [comment]
@qwales1 thanks Chris! i ended up using a variation of that (regex on a plugin called gulp-replace - it's more or less the same as gulp-regex-replace but probably less robust). it does the job "for now" but is a bit brittle in its current form...alas. i'll take a look at using the customAttributes option at a later date.
